CREATE DATABASE [Test_DB]
 ON  PRIMARY 
( NAME = N'Test_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Test_DB.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Test_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Test_DB_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
